### ISSUE TITLE
Usage with docker-compose

### ISSUE THREAD

**Issue by shawninder** [choonkeat/dbmigrate#7]
I'm trying to use docker-compose to have dbmigrate run some schema migration SQL scripts against a MariaDB instance running in another docker container, but for some reason, I can't connect to the database.

This might not be specific to dbmigrate - it feels like a problem with docker-compose networking - but maybe you have faced this kind of problem before?

Any pointers would be appreciated.

**docker-compose.yaml**
```
version: '3.5'

services:
    database:
        image: mariadb:latest
        container_name: users_database
        networks:
            backend:
                ipv4_address: 10.6.0.3
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=usersdb
            - MYSQL_USER=bob
            - MYSQL_PASSWORD=***********
            - MYSQL_ROOT_PASSWORD=***********
        volumes:
            - ./data/mysql:/var/lib/mysql

    schema:
        image: choonkeat/dbmigrate
        container_name: users_schema
        depends_on:
            - database
        environment:
            - DATABASE_DRIVER=mysql
            - DATABASE_URL='bob:***********@tcp(10.6.0.3:3306)/usersdb?multiStatements'
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./schema/migrations:/db/migrations
        command: ["-up"]

networks:
    backend:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.0.0/16
```

**schema logs**
```
Attaching to users_schema
schema_1    | 2019/05/25 02:46:38 unable to query existing versions: dial tcp 10.6.0.3:3306: connect: connection timed out
users_schema exited with code 1
```
